_target_: pretrain.models.possm.POSSM
backbone: gru
bin_width: 0.05
bin_step: 0.05
num_latents: 1
dim: 256
depth: 0
dim_head: 64
cross_heads: 1
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.0
rnn_dim: 384
num_rnn_layers: 4
rnn_dropout: 0.2
bidirectional: true
output_ca_ctx_lim: 3
