# @package _global_
defaults:
  - override /model: ndt_stitch_10M
  - _self_

trainer:
  _target_: ts1.models.pretrained.ndt_stitch.NDTStitchEvalTrainer

precision: bf16
num_epochs: 300
no_weight_decay: ["bias", "norm", "emb", "stitcher"]

finetuning:
  enable: true
  strategy:
    _target_: core.finetuning.FullFinetuning

val:
  start_patience: 50

ckpt:
  load_from: ${oc.env:BWB_NEURIPS_CKPT_DIR}/ndt_stitch.pt

# Lr grid for finetune.py with seed 42
sweep:
  base_lr: [5e-5, 1e-4, 2e-4, 5e-4, 1e-3]
