_target_: pretrain.models.nuclr.NuCLR
latent_step: 1.0   # in seconds
bin_size: 0.02
dim: 256
self_heads: 4
dim_head: 64
lin_dropout: 0.3
t_layers: 2
st_layers: 4
rot_ratio: 0.5
rotate_value: true
attn_biases: true
ctx_duration: null # set by trainer
