# @package _global_
defaults:
  - override /model: mtm_10M
  - _self_

trainer:
  _target_: ts2.models.pretrained.mtm.MtMEvalTrainer

precision: bf16
num_epochs: 300
base_lr: 1e-4
no_weight_decay: ["bias", "norm", "emb", "stitcher"]

finetuning:
  enable: true
  strategy:
    _target_: core.finetuning.FullFinetuning

val:
  start_patience: 50

ckpt:
  load_from: ${oc.env:BWB_NEURIPS_CKPT_DIR}/mtm.pt

sweep:
  base_lr: [1e-4, 2e-4, 5e-4, 1e-3, 2e-3]

masker:
  _target_: pretrain.models.mtm.MtMMasker

  mask_ratio: 0.5
  mask_types:
    - "neuron"
    - "causal"
    - "inter_region"
    - "intra_region"
  causal_ratio: 0.5
