# @package _global_
defaults:
  - override /model: possm_10M
  - _self_

trainer:
  _target_: ts1.models.pretrained.possm.POSSMEvalTrainer

precision: bf16

train_transforms:
  - _target_: torch_brain.transforms.UnitDropout
    max_units: 1800
    min_units: 300
    mode_units: 800
    peak: 4
